version: '3'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    volumes:
      #* We'll store the final 'dist' folder in a named volume
      - website:/PetProject/website/Dockerfile
    #* This container might not expose any port if it's only for building
    command: sh -c "npm run build && tail -f /dev/null"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      #* Mount the 'dist' folder into /usr/share/nginx/html/website
      - website:/PetProject/nginx/html/website

volumes:
  website:
