services:
  website:
    image: '${WEBSITE_IMAGE}'
    container_name: 'website'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # ports:
    #   - "3000:3000"

  nginx:
    image: '${NGINX_IMAGE}'
    container_name: 'nginx'
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - website
    volumes:
      - website:/usr/share/nginx/html/website
    environment:
      - NGINX_HOST=yourdomain.com
      - NGINX_PORT=80

volumes:
  website:
