version: '3'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: '${WEBSITE_IMAGE}'
    volumes:
      - website:/website/dist
    # ...

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: '${NGINX_IMAGE}'
    volumes:
      - website:/usr/share/nginx/html/website
    # ...

volumes:
  website:
