version: '3'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: '${WEBSITE_IMAGE}'
    volumes:
      - website:/PetProject/website/Dockerfile
    # ...

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: '${NGINX_IMAGE}'
    volumes:
      - nginx:/PetProject/nginx/Dockerfile
    # ...

volumes:
  website:
