version: '3'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: '${WEBSITE_IMAGE}'
    # This container builds your React files into /website/dist
    volumes:
      - dist:/website/dist
    command: sh -c "npm run build && tail -f /dev/null"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: '${NGINX_IMAGE}'
    ports:
      - '80:80'
    volumes:
      - dist:/usr/share/nginx/html

volumes:
  dist:
