name: Continuous Integration and Delivery

on:
  push:
    branches: [main]

env:
  WEBSITE_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/website
  NGINX_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/nginx
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build the Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set environment variables to .env
        run: |
          echo "WEBSITE_IMAGE=$(echo ${{ env.WEBSITE_IMAGE }})" >> $GITHUB_ENV
          echo "NGINX_IMAGE=$(echo ${{ env.NGINX_IMAGE }})" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.NAMESPACE }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Debug website folder
        run: |
          echo "List website folder"
          ls -al website

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull images
        run: |
          docker pull ${{ env.WEBSITE_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true

      - name: Build images
        run: |
          pwd
          ls -al
          docker-compose -f docker-compose.ci.yml build

      - name: Push images
        run: |
          docker push ${{ env.WEBSITE_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}

  checking-secrets:
    name: Checking secrets
    runs-on: ubuntu-latest
    needs: build
    outputs:
      secret_key_exists: ${{ steps.check_secrets.outputs.defined }}

    steps:
      - name: Check for Secrets availabilities
        id: check_secrets
        shell: bash
        run: |
          if [[ -n "${{ secrets.PRIVATE_KEY }}" && -n "${{ secrets.AWS_EC2_IP_ADDRESS }}" && -n "${{ secrets.AWS_HOST_USER }}" ]]; then
            echo "defined=true" >> $GITHUB_OUTPUT
          else
            echo "defined=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug NAMESPACE
        run: echo "NAMESPACE is ${{ secrets.NAMESPACE }}"

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: checking-secrets
    if: needs.checking-secrets.outputs.secret_key_exists == 'true'

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Add environment variables to .env
        run: |
          echo WEBSITE_IMAGE=${{ env.WEBSITE_IMAGE }} >> .env
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> .env
          echo NAMESPACE=${{ secrets.NAMESPACE }} >> .env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .env

      - name: Set up SSH Agent and Add Private Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Verify SSH Agent
        run: |
          ssh-add -l

      - name: Debug Secrets (for testing only, remove sensitive data afterward)
        run: |
          echo "AWS_HOST_USER: ${{ secrets.AWS_HOST_USER }}"
          echo "AWS_EC2_IP_ADDRESS: ${{ secrets.AWS_EC2_IP_ADDRESS }}"

      - name: Test SSH Connection
        run: |
          ssh -A -o StrictHostKeyChecking=no ${{ secrets.AWS_HOST_USER }}@${{ secrets.AWS_EC2_IP_ADDRESS }} 'echo "SSH connection successful."'

      - name: Copy .env and docker-compose.prod.yml to EC2
        run: |
          scp -A -o StrictHostKeyChecking=no -r .env docker-compose.prod.yml ${{ secrets.AWS_HOST_USER }}@${{ secrets.AWS_EC2_IP_ADDRESS }}:/home/${{ secrets.AWS_HOST_USER }}/

      - name: Deploy images on AWS EC2
        run: |
          # Copy .env and docker-compose.prod.yml to the EC2 instance
          scp -A -o StrictHostKeyChecking=no -r ./.env docker-compose.prod.yml ${{ secrets.AWS_HOST_USER }}@${{ secrets.AWS_EC2_IP_ADDRESS }}:/home/${{ secrets.AWS_HOST_USER }}/

          # Run Docker Compose commands on the remote EC2 server
          ssh -A -o StrictHostKeyChecking=no ${{ secrets.AWS_HOST_USER }}@${{ secrets.AWS_EC2_IP_ADDRESS }} <<EOF
          cd /home/${{ secrets.AWS_HOST_USER }}
          # Check if docker-compose is installed
          if ! command -v docker-compose >/dev/null 2>&1; then
          echo "docker-compose not found. Installing..."
          sudo curl -SL "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          fi
          # Optionally, ensure the installation directory is in PATH
          export PATH=\$PATH:/usr/local/bin
          # Print version for debugging
          docker-compose --version

          # Bring down any existing containers
          docker-compose down --rmi all -v

          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin

           # Pull the latest images
          docker-compose --env-file=.env -f docker-compose.prod.yml pull

          # Start the containers
          docker-compose --env-file=.env -f docker-compose.prod.yml up -d

          # Log out from Docker registry
          docker logout
          EOF

      - name: Build and push images
        run: |
          docker build -t ghcr.io/SkyMantle/PetProject/website ./website
          docker push ghcr.io/SkyMantle/PetProject/website
